export const ESCROW_ABI = [
  // Events
  {
    type: "event",
    name: "Locked",
    inputs: [
      { name: "amount", type: "uint256", indexed: false },
      { name: "actor", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "Submitted",
    inputs: [
      { name: "index", type: "uint256", indexed: true },
      { name: "code", type: "string", indexed: false },
      { name: "evidenceHash", type: "bytes32", indexed: false },
      { name: "actor", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "Released",
    inputs: [
      { name: "index", type: "uint256", indexed: true },
      { name: "code", type: "string", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "actor", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "Cancelled",
    inputs: [
      { name: "reason", type: "string", indexed: false },
      { name: "refundAmount", type: "uint256", indexed: false },
      { name: "actor", type: "address", indexed: true },
    ],
  },
  // Read functions
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buyer",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "producer",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lockedAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "releasedAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "refundedAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelled",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "milestonesLength",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "milestone",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [
      { name: "code", type: "string" },
      { name: "bps", type: "uint256" },
      { name: "state", type: "uint8" },
      { name: "evidenceHash", type: "bytes32" },
      { name: "submittedAt", type: "uint256" },
      { name: "approvedAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSummary",
    inputs: [],
    outputs: [
      { name: "_token", type: "address" },
      { name: "_buyer", type: "address" },
      { name: "_producer", type: "address" },
      { name: "_admin", type: "address" },
      { name: "_totalAmount", type: "uint256" },
      { name: "_lockedAmount", type: "uint256" },
      { name: "_releasedAmount", type: "uint256" },
      { name: "_refundedAmount", type: "uint256" },
      { name: "_cancelled", type: "bool" },
      { name: "_milestonesCount", type: "uint256" },
    ],
    stateMutability: "view",
  },
  // Write functions
  {
    type: "function",
    name: "lock",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submit",
    inputs: [
      { name: "index", type: "uint256" },
      { name: "evidenceHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approve",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancel",
    inputs: [{ name: "reason", type: "string" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export const ERC20_ABI = [
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
